TUNING.PUREECOMOMICS={}

TUNING.PUREECOMOMICS.UNLOCK_EVERYTHING = GetModConfigData("unlock") or false
TUNING.PUREECOMOMICS.DISABLE_COFFEE = GetModConfigData("disablecoffee") or false
TUNING.PUREECOMOMICS.DISABLE_SLOTMACHINE = GetModConfigData("disableslotmachine") or false
TUNING.PUREECOMOMICS.PRECIOUS_SLOT_NUM = GetModConfigData("preciousslot") or 12

if TUNING.PUREECOMOMICS.PRECIOUS_SLOT_NUM == -1 then
    TUNING.PUREECOMOMICS.UNLOCK_PRECIOUS = true
else
    TUNING.PUREECOMOMICS.UNLOCK_PRECIOUS = false
end

TUNING.PUREECOMOMICS.PRECIOUS_REFRESH_PERIOD = GetModConfigData("preciousperiod") or 5
TUNING.PUREECOMOMICS.BASE_MULTIPLE = .5
TUNING.PUREECOMOMICS.PRECIOUS_MULTIPLE = .3

 
TUNING.PUREECOMOMICS.USER_MODE = 1
TUNING.PUREECOMOMICS.ADMIN_MODE = 0