TUNING.PUREECOMOMICS={}

TUNING.PUREECOMOMICS.UNLOCKEVERYTHING = GetModConfigData("unlock") or false
TUNING.PUREECOMOMICS.DISABLECOFFEE = GetModConfigData("disablecoffee") or false
TUNING.PUREECOMOMICS.DISABLESLOTMACHINE = GetModConfigData("disableslotmachine") or false
TUNING.PUREECOMOMICS.BASE_MULTIPLE = .5
TUNING.PUREECOMOMICS.PRECIOUS_MULTIPLE = .3


TUNING.PUREECOMOMICS.USER_MODE = 1
TUNING.PUREECOMOMICS.ADMIN_MODE = 0