STRINGS.NAMES.COFFEEBUSH = "咖啡丛"
STRINGS.NAMES.COFFEEBEANS = "咖啡豆"
STRINGS.NAMES.COFFEEBEANS_COOKED = "烤过的咖啡豆"
STRINGS.NAMES.COFFEE = "普通咖啡"
STRINGS.NAMES.PE_SLOTMACHINE= "欧洲人筛选器"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.COFFEEBEANS = "可以烘烤一下它们。"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.COFFEEBEANS_COOKED = "高温必定提升了它们的质量。"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.COFFEEBUSH = "源自火山的植物。"
STRINGS.NAMES.DUG_COFFEEBUSH = "咖啡丛"
STRINGS.RECIPE_DESC.DUG_COFFEEBUSH = "生产可以提神的咖啡豆。"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DUG_COFFEEBUSH = "它源自火山！"

STRINGS.NAMES.OINC_YUAN = "币"
STRINGS.RECIPE_DESC.OINC_YUAN = "币"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.OINC_YUAN = "我可以拿它买点东西"
STRINGS.NAMES.OINC10_YUAN = "10币"
STRINGS.RECIPE_DESC.OINC10_YUAN = "10币"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.OINC10_YUAN = "我可以拿它买不少东西"
STRINGS.NAMES.OINC100_YUAN = "100币"
STRINGS.RECIPE_DESC.OINC100_YUAN = "100币"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.OINC100_YUAN = "我可以拿它买一大堆东西"

STRINGS.NAMES.SHOP_PEDESTAL = "售卖桌"
STRINGS.RECIPE_DESC.SHOP_PEDESTAL="卖东西"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SHOP_PEDESTAL = "卖东西的地方"

STRINGS.PUREECOMOMICS = {}
STRINGS.PUREECOMOMICS.SELL_BUTTON = "售卖"
STRINGS.PUREECOMOMICS.SELL_SUCCESS = "交易成功！总计"
STRINGS.PUREECOMOMICS.SELL_FAILURE = "交易失败"
STRINGS.PUREECOMOMICS.UNIT = "元"

STRINGS.PUREECOMOMICS.SHOP_BUTTON = "商店"
STRINGS.PUREECOMOMICS.REAMIN_INFO = "余额"
STRINGS.PUREECOMOMICS.SUBMIT_BUTTON = "提交"
STRINGS.PUREECOMOMICS.CHECKBOX_LABEL = "可购买"
STRINGS.PUREECOMOMICS.EDIT_BUTTON = "编辑价格"
STRINGS.PUREECOMOMICS.LAST_BUTTON = "上一页"
STRINGS.PUREECOMOMICS.NEXT_BUTTON = "下一页"
STRINGS.PUREECOMOMICS.FINISH_EDIT_BUTTON = "返回商店"
STRINGS.PUREECOMOMICS.RECOVERY_BUTTON = "撤销修改"

STRINGS.PUREECOMOMICS.SELLRATE_INFO_1 = "售卖倍率:"
STRINGS.PUREECOMOMICS.FILTERS= {
	food = "食物",
	smithing = "穿戴",
	resource = "资源",
	fight = "战斗",
	tool = "工具",
	decoration = "装饰",
	precious = "珍贵",
	special = "特殊",
}